#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
config dictionaries and corresponding functions

"""

### FUCTIONS TO APPLY TO DATA AFTER READING
def fixvald(data):
    return data

def fixsources(data):
    return data

def fixrefs(data):
    return data

def fixnothing(data):
    return data

def fixspecies(data):
    return data

### CONFIG "FILES"
dummycfg = {\
    'tables':[\
        {'fname':'dummy.dat',
         'delim':' ',
         'tname':'dummy1',
         'headlines':0,
         'commentchar':'#',
         'function':fixnothing,
         'columns':[\
                {'cname':'c11',
                 'cfmt':'d',
                 'ccom':'column 1',
                 'cunit':None,
                 'cbyte':0,
                 'cnull':None,
                 'ctype':'UNSIGNED INT',
                 },
                {'cname':'c12',
                 'cfmt':'.2f',
                 'ccom':'column 2',
                 'cunit':'Å',
                 'cbyte':1,
                 'cnull':0.0,
                 'ctype':'FLOAT',
                 },
                ]
         },
        {'fname':'dummy.dat',
         'delim':' ',
         'tname':'dummy2',
         'headlines':0,
         'commentchar':'',
         'function':fixnothing,
         'columns':[\
                {'cname':'c21',
                 'cfmt':'d',
                 'ccom':'column 1',
                 'cunit':None,
                 'cbyte':0,
                 'cnull':None,
                 'ctype':'UNSIGNED INT',
                 },
                {'cname':'c22',
                 'cfmt':'.2f',
                 'ccom':'column 2',
                 'cunit':'eV',
                 'cbyte':2,
                 'cnull':0.0,
                 'ctype':'FLOAT',
                 },
                ],
         'relations':[{\
                'table1':'dummy1',
                'column1':'c1',
                'table2':'dummy2',
                'column2':'c1'
                }]
      
         }
        ]
    }

vald3cfg={         # start dictionary
    'tables':[    # start list of tables
        {         # start dictionary for first table
        'tname':'transitions',       # table name in db
         'fname':'/home/tom/vald3.dat',  # file to read data from
         'delim':'fixedcol',    # delimiter character or 'fixedcol'
         'headlines':2,         # this many lies ignored in file header
         'commentchar':'#',     # lines that start with this are ignored
         'function':fixvald,    # to be applied on each line
         'columns':[            # start list of columns
                {               # start dictionary for first column
                 'cname':'vacwave',     # column name
                 'cfmt':'.8f',        # print format
                 'ccom':'Vacuum Wavelength', # description
                 'cunit':'Å',         # Units
                 'cbyte':(0,15),      # place in the line
                 'cnull':None,        # value to be converted to NULL
                 'ctype':'DOUBLE',     # data format in database
                 },  
                {               # start dictionary for first column
                 'cname':'airwave',     # column name
                 'cfmt':'.8f',        # print format
                 'ccom':'Air Wavelength', # description
                 'cunit':'Å',         # Units
                 'cbyte':(15,30),      # place in the line
                 'cnull':None,        # value to be converted to NULL
                 'ctype':'DOUBLE',     # data format in database
                 },  
                {'cname':'species',
                 'cfmt':'d',
                 'ccom':'species identifier',
                 'cunit':None,
                 'cbyte':(30,36),
                 'cnull':None,
                 'ctype':'SMALLINT UNSIGNED'},
                {'cname':'loggf',
                 'cfmt':'.3f',
                 'ccom':'oscillator strength, log g*f',
                 'cunit':None,
                 'cbyte':(36,44),
                 'cnull':None,
                 'ctype':'FLOAT'},
                {'cname':'elow',
                 'cfmt':'.4f',
                 'ccom':'excitation energy of the lower level',
                 'cunit':'cm^-1',
                 'cbyte':(44,58),
                 'cnull':None,
                 'ctype':'FLOAT UNSIGNED'},
                {'cname':'jlow',
                 'cfmt':'.1f',
                 'ccom':'quantum number J of the lower level',
                 'cunit':None,
                 'cbyte':(58,63),
                 'cnull':None,
                 'ctype':'FLOAT UNSIGNED'},
                {'cname':'ehi',
                 'cfmt':'.4f',
                 'ccom':'excitation energy of the upper level',
                 'cunit':'cm^-1',
                 'cbyte':(63,77),
                 'cnull':None,
                 'ctype':'FLOAT UNSIGNED'},
                {'cname':'jhi',
                 'cfmt':'.1f',
                 'ccom':'quantum number J of the upper level',
                 'cunit':None,
                 'cbyte':(77,82),
                 'cnull':None,
                 'ctype':'FLOAT UNSIGNED'},
                {'cname':'landlo',
                 'ccom':'Lande factor, lower level',
                 'cfmt':'.2f',
                 'cunit':None,
                 'cbyte':(82,88),
                 'cnull':99.00,
                 'ctype':'FLOAT'},
                {'cname':'landhi',
                 'ccom':'Lande factor, higher level',
                 'cfmt':'.2f',
                 'cunit':None,
                 'cbyte':(88,94),
                 'cnull':99.00,
                 'ctype':'FLOAT'},
                {'cname':'landeff',
                 'ccom':'effective Lande factor',
                 'cfmt':'.2f',
                 'cunit':None,
                 'cbyte':(94,100),
                 'cnull':99.00,
                 'ctype':'FLOAT'},
                {'cname':'gammarad',
                 'cfmt':'.3f',
                 'ccom':'line broadening gamma: radiative damping constant',
                 'cunit':None,
                 'cbyte':(100,107),
                 'cnull':0.0,
                 'ctype':'FLOAT'},
                {'cname':'gammastark',
                 'cfmt':'.3f',
                 'ccom':'line broadening gamma: stark damping constant',
                 'cunit':None,
                 'cbyte':(107,114),
                 'cnull':0.0,
                 'ctype':'FLOAT'},
                {'cname':'gammawaals',
                 'cfmt':'.3f',
                 'ccom':'line broadening gamma: Van der Waals damping constant',
                 'cunit':None,
                 'cbyte':(114,122),
                 'cnull':0.0,
                 'ctype':'FLOAT'},
                {'cname':'couplo',
                 'cfmt':'s',
                 'ccom':'coupling, lower level',
                 'cunit':None,
                 'cbyte':(122,124),
                 'cnull':'  ',
                 'ctype':'CHAR(2)'},
                {'cname':'termlo',
                 'cfmt':'s',
                 'ccom':'level and term, lower',
                 'cunit':None,
                 'cbyte':(124,170),
                 'cnull':' '*46,
                 'ctype':'CHAR(46)'},
                {'cname':'couphi',
                 'cfmt':'s',
                 'ccom':'coupling, higher level',
                 'cunit':None,
                 'cbyte':(170,172),
                 'cnull':'  ',
                 'ctype':'CHAR(2)'},
                {'cname':'termhi',
                 'cfmt':'s',
                 'ccom':'level and term, higher',
                 'cunit':None,
                 'cbyte':(172,218),
                 'cnull':' '*46,
                 'ctype':'CHAR(46)'},
                {'cname':'srctag',
                 'cfmt':'s',
                 'ccom':'source tag',
                 'cunit':None,
                 'cbyte':(218,225),
                 'cnull':' '*7,
                 'ctype':'CHAR(7)'},
                {'cname':'acflag',
                 'cfmt':'s',
                 'ccom':'accuracy flag',
                 'cunit':None,
                 'cbyte':(225,226),
                 'cnull':' ',
                 'ctype':'CHAR(1)'},
                {'cname':'accur',
                 'cfmt':'s',
                 'ccom':'accuracy string',
                 'cunit':None,
                 'cbyte':(226,236),
                 'cnull':' '*10,
                 'ctype':'CHAR(10)'},
                {'cname':'comment',
                 'cfmt':'s',
                 'ccom':'comment string',
                 'cunit':None,
                 'cbyte':(236,252),
                 'cnull':' '*10,
                 'ctype':'CHAR(10)'},
                {'cname':'wave_ref',
                 'cfmt':'d',
                 'ccom':'reference code for the wavelength',
                 'cunit':None,
                 'cbyte':(252,256),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'loggf_ref',
                 'cfmt':'d',
                 'ccom':'reference code for log g*f',
                 'cunit':None,
                 'cbyte':(256,260),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'elo_ref',
                 'cfmt':'d',
                 'ccom':'reference code for the lower energy',
                 'cunit':None,
                 'cbyte':(260,264),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ehi_ref',
                 'cfmt':'d',
                 'ccom':'reference code for the higher energy',
                 'cunit':None,
                 'cbyte':(264,268),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'lande_ref',
                 'cfmt':'d',
                 'ccom':'reference code for the lande factors',
                 'cunit':None,
                 'cbyte':(268,272),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'gammarad_ref',
                 'cfmt':'d',
                 'ccom':'reference code for radiative gamma',
                 'cunit':None,
                 'cbyte':(272,276),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'gamastark_ref',
                 'cfmt':'d',
                 'ccom':'reference code for stark gamma',
                 'cunit':None,
                 'cbyte':(276,280),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'gammawaals_ref',
                 'cfmt':'d',
                 'ccom':'reference code for van der waals gamma',
                 'cunit':None,
                 'cbyte':(280,284),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'level_ref',
                 'cfmt':'d',
                 'ccom':'reference code for the level designations',
                 'cunit':None,
                 'cbyte':(284,288),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},

                ],
        },
        {        
            'tname':'species',     
            'fname':'/home/tom/VALD_list_of_species', 
            'delim':'fixedcol',  
            'headlines':0,   
            'commentchar':'#',   
            'function':fixspecies,  
            'columns':[          
                {'cname':'id',  
                 'cfmt':'d',       
                 'ccom':'VALD species number', 
                 'cunit':None,      
                 'cbyte':(0,7),   
                 'cnull':None,     
                 'ctype':'SMALLINT UNSIGNED'},  
                {'cname':'name',  
                 'cfmt':'s',       
                 'ccom':'Name', 
                 'cunit':None,      
                 'cbyte':(9,19),   
                 'cnull':None,     
                 'ctype':'CHAR(10)'}, 
                {'cname':'ion',  
                 'cfmt':'d',       
                 'ccom':'ionization', 
                 'cunit':None,      
                 'cbyte':(20,22),   
                 'cnull':None,     
                 'ctype':'SMALLINT UNSIGNED'},  
                {'cname':'mass',  
                 'cfmt':'.3f',       
                 'ccom':'mass in atomic units', 
                 'cunit':None,      
                 'cbyte':(23,30),   
                 'cnull':None,     
                 'ctype':'DOUBLE'},  
                {'cname':'ionen',  
                 'cfmt':'.4f',       
                 'ccom':'ionization energy', 
                 'cunit':None,      
                 'cbyte':(31,40),   
                 'cnull':None,     
                 'ctype':'DOUBLE'},  
                {'cname':'solariso',  
                 'cfmt':'.4f',       
                 'ccom':'solar isotopic fraction', 
                 'cunit':None,      
                 'cbyte':(41,46),   
                 'cnull':None,     
                 'ctype':'DOUBLE'},  
                {'cname':'ncomp',  
                 'cfmt':'d',       
                 'ccom':'number of components', 
                 'cunit':None,      
                 'cbyte':(132,133),   
                 'cnull':None,     
                 'ctype':'TINYINT UNSIGNED'},  
                {'cname':'atomic',  
                 'cfmt':'d',       
                 'ccom':'atomic number', 
                 'cunit':None,      
                 'cbyte':(134,136),   
                 'cnull':None,     
                 'ctype':'TINYINT UNSIGNED'},  
                {'cname':'isotope',  
                 'cfmt':'d',       
                 'ccom':'isotope', 
                 'cunit':None,      
                 'cbyte':(137,140),   
                 'cnull':None,     
                 'ctype':'TINYINT UNSIGNED'},  
                ],
        },
        {'tname':'sources',
         'fname':'/home/tom/vald3_test.cfg',
         'delim':',',
         'headlines':1,
         'commentchar':';',
         'function':fixsources,
         'columns':[\
                {'cname':'srcfile',
                 'cfmt':'s',
                 'ccom':'vald source file name',
                 'cunit':None,
                 'cbyte':0,
                 'cnull':None,
                 'ctype':'VARCHAR(128)'},
                {'cname':'refid',
                 'cfmt':'d',
                 'ccom':'VALD internal reference ID',
                 'cunit':None,
                 'cbyte':1,
                 'cnull':None,
                 'ctype':'SMALLINT UNSIGNED'},
                {'cname':'speclo',
                 'cfmt':'d',
                 'ccom':'species range lower bound',
                 'cunit':None,
                 'cbyte':2,
                 'cnull':None,
                 'ctype':'SMALLINT UNSIGNED'},
                {'cname':'spechi',
                 'cfmt':'d',
                 'ccom':'species range upper bound',
                 'cunit':None,
                 'cbyte':3,
                 'cnull':None,
                 'ctype':'SMALLINT UNSIGNED'},
                {'cname':'blob',
                 'cfmt':'d',
                 'ccom':'some number descibing the list, 0 means linelist, 1 replacement list, etc',
                 'cunit':None,
                 'cbyte':4,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r1',
                 'cfmt':'d',
                 'ccom':'rank1',
                 'cunit':None,
                 'cbyte':5,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r2',
                 'cfmt':'d',
                 'ccom':'rank2',
                 'cunit':None,
                 'cbyte':6,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r3',
                 'cfmt':'d',
                 'ccom':'rank3',
                 'cunit':None,
                 'cbyte':7,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r4',
                 'cfmt':'d',
                 'ccom':'rank4',
                 'cunit':None,
                 'cbyte':8,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r5',
                 'cfmt':'d',
                 'ccom':'rank5',
                 'cunit':None,
                 'cbyte':9,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r6',
                 'cfmt':'d',
                 'ccom':'rank6',
                 'cunit':None,
                 'cbyte':10,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r7',
                 'cfmt':'d',
                 'ccom':'rank7',
                 'cunit':None,
                 'cbyte':11,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r8',
                 'cfmt':'d',
                 'ccom':'rank8',
                 'cunit':None,
                 'cbyte':12,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'r9',
                 'cfmt':'d',
                 'ccom':'rank9',
                 'cunit':None,
                 'cbyte':13,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'srcdescr',
                 'cfmt':'s',
                 'ccom':'vald source comment',
                 'cunit':None,
                 'cbyte':14,
                 'cnull':None,
                 'ctype':'VARCHAR(128)'},
                ]
         },
        ],
    'relations':[ # descibe which table.column is related to another
        {'t1':'sources',
         'c1':'refid',
         't2':'transitions',
         'c2':'wave_ref',
         },
        {'t1':'species',
         'c1':'id',
         't2':'transitions',
         'c2':'species',
         }
        ]
    }




# OLD VALD 2 ##########################################3        
valdcfg={         # start dictionary
    'tables':[    # start list of tables
        {         # start dictionary for first table
        'tname':'valddata',       # table name in db
         'fname':'valdsample.dat',  # file to read data from
         'delim':'fixedcol',    # delimiter character or 'fixedcol'
         'headlines':2,         # this many lies ignored in file header
         'commentchar':'#',     # lines that start with this are ignored
         'function':fixvald,    # to be applied on each line
         'columns':[            # start list of columns
                {               # start dictionary for first column
                 'cname':'wavel',     # column name
                 'cfmt':'.5f',        # print format
                 'ccom':'Wavelength', # description
                 'cunit':'Å',         # Units
                 'cbyte':(0,13),      # place in the line
                 'cnull':None,        # value to be converted to NULL
                 'ctype':'FLOAT',     # data format in database
                 },                 
                {'cname':'atomic',
                 'cfmt':'d',
                 'ccom':'Atomic number',
                 'cunit':None,
                 'cbyte':(13,16),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ion',
                 'cfmt':'d',
                 'ccom':'Ionization stage, 0 is neutral',
                 'cunit':None,
                 'cbyte':(17,19),
                 'cnull':None,
                 'ctype':'SMALLINT UNSIGNED'},
                {'cname':'loggf',
                 'cfmt':'.3f',
                 'ccom':'oscillator strength, log g*f',
                 'cunit':None,
                 'cbyte':(19,27),
                 'cnull':None,
                 'ctype':'FLOAT'},
                {'cname':'lowev',
                 'cfmt':'.3f',
                 'ccom':'excitation energy of the lower level',
                 'cunit':'eV',
                 'cbyte':(27,35),
                 'cnull':None,
                 'ctype':'FLOAT UNSIGNED'},
                {'cname':'lowj',
                 'cfmt':'.2f',
                 'ccom':'quantum number J of the lower level',
                 'cunit':None,
                 'cbyte':(35,40),
                 'cnull':None,
                 'ctype':'FLOAT UNSIGNED'},
                {'cname':'hiev',
                 'cfmt':'.3f',
                 'ccom':'excitation energy of the upper level',
                 'cunit':'eV',
                 'cbyte':(40,48),
                 'cnull':None,
                 'ctype':'FLOAT UNSIGNED'},
                {'cname':'hij',
                 'ccom':'quantum number J of the upper level',
                 'cfmt':'.2f',
                 'cunit':None,
                 'cbyte':(48,53),
                 'cnull':None,
                 'ctype':'FLOAT UNSIGNED'},
                {'cname':'landup',
                 'ccom':'Lande factor, upper level',
                 'cfmt':'.2f',
                 'cunit':None,
                 'cbyte':(53,59),
                 'cnull':99.00,
                 'ctype':'FLOAT'},
                {'cname':'landlo',
                 'ccom':'Lande factor, lower level',
                 'cfmt':'.2f',
                 'cunit':None,
                 'cbyte':(59,65),
                 'cnull':99.00,
                 'ctype':'FLOAT'},
                {'cname':'landeff',
                 'ccom':'effective Lande factor',
                 'cfmt':'.2f',
                 'cunit':None,
                 'cbyte':(65,71),
                 'cnull':99.00,
                 'ctype':'FLOAT'},
                {'cname':'broadrad',
                 'cfmt':'.3f',
                 'ccom':'line broadening: radiative damping constant',
                 'cunit':None,
                 'cbyte':(71,78),
                 'cnull':0.0,
                 'ctype':'FLOAT'},
                {'cname':'broadstark',
                 'cfmt':'.3f',
                 'ccom':'line broadening: stark damping constant',
                 'cunit':None,
                 'cbyte':(78,85),
                 'cnull':0.0,
                 'ctype':'FLOAT'},
                {'cname':'broadwaals',
                 'cfmt':'.3f',
                 'ccom':'line broadening: Van der Waals damping constant',
                 'cunit':None,
                 'cbyte':(85,93),
                 'cnull':0.0,
                 'ctype':'FLOAT'},
                {'cname':'transdesc',
                 'cfmt':'.2f',
                 'ccom':'transition description, plus subselection of reference',
                 'cunit':None,
                 'cbyte':(93,123),
                 'cnull':None,
                 'ctype':'CHAR(30)'},
                {'cname':'ref1',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(123,127),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ref2',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(127,131),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ref3',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(131,135),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ref4',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(135,139),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ref5',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(139,143),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ref6',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(143,147),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ref7',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(147,151),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ref8',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(151,155),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'ref9',
                 'cfmt':'d',
                 'ccom':'reference to VALD source file, i.e. reference',
                 'cunit':None,
                 'cbyte':(155,159),
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                ]
        },
        {'tname':'refs',
         'fname':'vald.refs',
         'delim':',',
         'headlines':1,
         'commentchar':';',
         'function':fixrefs,
         'columns':[\
                {'cname':'srcfile',
                 'cfmt':'s',
                 'ccom':'vald source file name',
                 'cunit':None,
                 'cbyte':0,
                 'cnull':None,
                 'ctype':'VARCHAR(64)'},
                {'cname':'d1',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':1,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d2',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':2,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d3',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':3,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d4',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':4,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d5',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':5,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d6',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':6,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d7',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':7,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d8',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':8,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d9',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':9,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d10',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':10,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d11',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':11,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'d12',
                 'cfmt':'d',
                 'ccom':'',
                 'cunit':None,
                 'cbyte':12,
                 'cnull':None,
                 'ctype':'TINYINT UNSIGNED'},
                {'cname':'srcdescr',
                 'cfmt':'s',
                 'ccom':'vald source comment',
                 'cunit':None,
                 'cbyte':13,
                 'cnull':None,
                 'ctype':'VARCHAR(128)'},
                ]
         },
        ],
    'relations':[ # descibe which table.column is related to another
        {'table1':'merged',
         'column1':'ref1',
         'table2':'meta',
         'column2':'d1',
         }
        ]
    }
