# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyscan',
            name='product_charge',
            field=models.IntegerField(choices=[(0, 'Neutral'), (-1, 'Anionic'), (1, 'Cationic')], default=-1),
        ),
    ]
