# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_energyscan_product_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyscan',
            name='process_code',
            field=models.IntegerField(choices=[(0, 'Electron Attachment'), (1, 'Dissociation'), (2, 'Ionization')], default=0),
        ),
        migrations.AddField(
            model_name='energyscan',
            name='process_code_2',
            field=models.IntegerField(blank=True, choices=[(0, 'Electron Attachment'), (1, 'Dissociation'), (2, 'Ionization')], null=True),
        ),
    ]
