# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0003_auto_20170807_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyscan',
            name='process_code',
            field=models.CharField(choices=[('elat', 'Electron Attachment'), ('diss', 'Dissociation'), ('ioni', 'Ionization')], default='elat', max_length=4),
        ),
        migrations.AlterField(
            model_name='energyscan',
            name='process_code_2',
            field=models.CharField(blank=True, choices=[('elat', 'Electron Attachment'), ('diss', 'Dissociation'), ('ioni', 'Ionization')], default='', max_length=4),
            preserve_default=False,
        ),
    ]
