# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0005_species_vamdc_species_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='inchikey',
            new_name='inchikey_neutral',
        ),
    ]
