# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0006_auto_20170808_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='species',
            old_name='vamdc_species_id',
            new_name='inchikey_negative',
        ),
    ]
