# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0007_auto_20170808_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='inchikey_positive',
            field=models.CharField(blank=True, db_index=True, max_length=27, verbose_name='VAMDC Species ID'),
        ),
    ]
