# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0010_auto_20170809_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='inchi_negative',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='InChI anion'),
        ),
        migrations.AddField(
            model_name='species',
            name='inchi_positive',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='InChI cation'),
        ),
        migrations.AlterField(
            model_name='species',
            name='inchi_neutral',
            field=models.CharField(blank=True, db_index=True, max_length=300, verbose_name='InChI neutral'),
        ),
    ]
