# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0011_auto_20170809_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='inchi_negative',
            field=models.CharField(blank=True, max_length=300, verbose_name='InChI anion'),
        ),
        migrations.AlterField(
            model_name='species',
            name='inchi_positive',
            field=models.CharField(blank=True, max_length=300, verbose_name='InChI cation'),
        ),
        migrations.AlterField(
            model_name='species',
            name='inchikey_negative',
            field=models.CharField(blank=True, max_length=27, verbose_name='InChI-Key anion'),
        ),
        migrations.AlterField(
            model_name='species',
            name='inchikey_positive',
            field=models.CharField(blank=True, max_length=27, verbose_name='InChI-Key cation'),
        ),
    ]
