# Generated by Django 5.2.7 on 2025-11-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineList',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('srcfile', models.CharField(max_length=128)),
                ('listtype', models.CharField(blank=True, max_length=32, null=True)),
                ('method', models.PositiveSmallIntegerField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'linelists',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.CharField(db_index=True, max_length=7, primary_key=True, serialize=False)),
                ('bibtex', models.TextField(null=True)),
                ('xml', models.TextField(null=True)),
            ],
            options={
                'db_table': 'refs',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('ion', models.PositiveSmallIntegerField(db_index=True)),
                ('inchi', models.CharField(db_index=True, max_length=32)),
                ('inchikey', models.CharField(db_index=True, max_length=28)),
                ('mass', models.DecimalField(db_index=True, decimal_places=5, max_digits=8)),
                ('massno', models.PositiveSmallIntegerField(db_index=True, null=True)),
                ('ionen', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('solariso', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('ncomp', models.PositiveSmallIntegerField(null=True)),
                ('atomic', models.PositiveSmallIntegerField(db_index=True, null=True)),
                ('isotope', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='SpeciesComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atom', to='node_common.species')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='molec', to='node_common.species')),
            ],
            options={
                'db_table': 'species_components',
            },
        ),
        migrations.AddField(
            model_name='species',
            name='components',
            field=models.ManyToManyField(through='node_common.SpeciesComp', to='node_common.species'),
        ),
    ]
