# Generated by Django 5.2.7 on 2025-11-13 09:38

import django.db.models.deletion
import node.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineList',
            fields=[
                ('id', models.PositiveSmallIntegerField(db_index=True, primary_key=True, serialize=False)),
                ('srcfile', models.CharField(max_length=128)),
                ('listtype', models.CharField(blank=True, max_length=32, null=True)),
                ('method', models.PositiveSmallIntegerField(db_index=True, null=True)),
            ],
            options={
                'db_table': 'linelists',
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.CharField(db_index=True, max_length=7, primary_key=True, serialize=False)),
                ('bibtex', models.TextField(null=True)),
                ('xml', models.TextField(null=True)),
            ],
            options={
                'db_table': 'refs',
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('ion', models.PositiveSmallIntegerField(db_index=True)),
                ('inchi', models.CharField(db_index=True, max_length=32)),
                ('inchikey', models.CharField(db_index=True, max_length=28)),
                ('mass', models.DecimalField(db_index=True, decimal_places=5, max_digits=8)),
                ('massno', models.PositiveSmallIntegerField(db_index=True, null=True)),
                ('ionen', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('solariso', models.DecimalField(decimal_places=4, max_digits=6, null=True)),
                ('ncomp', models.PositiveSmallIntegerField(null=True)),
                ('atomic', models.PositiveSmallIntegerField(db_index=True, null=True)),
                ('isotope', models.PositiveSmallIntegerField(null=True)),
            ],
            options={
                'db_table': 'species',
            },
        ),
        migrations.CreateModel(
            name='SpeciesComp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='atom', to='node.species')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='molec', to='node.species')),
            ],
            options={
                'db_table': 'species_components',
            },
        ),
        migrations.AddField(
            model_name='species',
            name='components',
            field=models.ManyToManyField(through='node.SpeciesComp', to='node.species'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('energy', models.DecimalField(db_index=True, decimal_places=4, max_digits=15, null=True)),
                ('energy_scaled', models.BigIntegerField(db_index=True, null=True)),
                ('lande', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('config', models.CharField(max_length=86, null=True)),
                ('term', models.CharField(max_length=86, null=True)),
                ('hfs_a', models.FloatField(db_column='hfs_A', null=True)),
                ('hfs_a_error', models.FloatField(db_column='hfs_dA', null=True)),
                ('hfs_b', models.FloatField(db_column='hfs_B', null=True)),
                ('hfs_b_error', models.FloatField(db_column='hfs_dB', null=True)),
                ('energy_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('lande_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('level_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('energy_method', models.PositiveSmallIntegerField(db_index=True, null=True)),
                ('j', models.DecimalField(db_column='J', decimal_places=1, max_digits=3, null=True)),
                ('s', models.DecimalField(db_column='S', decimal_places=1, max_digits=3, null=True)),
                ('p', models.DecimalField(db_column='P', decimal_places=1, max_digits=3, null=True)),
                ('n', models.PositiveSmallIntegerField(db_column='n', null=True)),
                ('l', models.PositiveSmallIntegerField(db_column='L', null=True)),
                ('j1', models.DecimalField(db_column='J1', decimal_places=1, max_digits=3, null=True)),
                ('j2', models.DecimalField(db_column='J2', decimal_places=1, max_digits=3, null=True)),
                ('k', models.DecimalField(db_column='K', decimal_places=1, max_digits=3, null=True)),
                ('s2', models.DecimalField(db_column='S2', decimal_places=1, max_digits=3, null=True)),
                ('jc', models.DecimalField(db_column='Jc', decimal_places=1, max_digits=3, null=True)),
                ('sn', models.PositiveSmallIntegerField(db_column='Sn', null=True)),
                ('v', models.PositiveSmallIntegerField(db_column='v', null=True)),
                ('Lambda', models.PositiveSmallIntegerField(db_column='Lambda', null=True)),
                ('Sigma', models.DecimalField(db_column='Sigma', decimal_places=1, max_digits=3, null=True)),
                ('Omega', models.DecimalField(db_column='Omega', decimal_places=1, max_digits=3, null=True)),
                ('rotN', models.PositiveSmallIntegerField(db_column='rotN', null=True)),
                ('elecstate', models.CharField(max_length=10, null=True)),
                ('species', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='node.species')),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wave', models.DecimalField(db_index=True, decimal_places=8, max_digits=16)),
                ('waveritz', models.DecimalField(db_index=True, decimal_places=8, max_digits=16)),
                ('loggf', models.DecimalField(decimal_places=3, max_digits=8, null=True)),
                ('einsteina', models.FloatField(db_index=True, null=True)),
                ('gammarad', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('gammastark', models.DecimalField(decimal_places=3, max_digits=7, null=True)),
                ('gammawaals', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('sigmawaals', models.PositiveSmallIntegerField(null=True)),
                ('alphawaals', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('accurflag', models.CharField(max_length=1, null=True)),
                ('accur', models.CharField(max_length=10, null=True)),
                ('loggf_err', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('wave_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('waveritz_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('loggf_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('gammarad_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('gammastark_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('waals_ref_id', node.models.RefCharField(max_length=7, null=True)),
                ('transition_type', models.CharField(max_length=2, null=True)),
                ('autoionized', models.BooleanField(default=False, null=True)),
                ('wave_method', models.PositiveSmallIntegerField(db_index=True, null=True)),
                ('lostate', models.ForeignKey(db_column='lostate', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='islowerstate_trans', to='node.state')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='node.species')),
                ('upstate', models.ForeignKey(db_column='upstate', db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='isupperstate_trans', to='node.state')),
            ],
            options={
                'db_table': 'transitions',
            },
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['species', 'energy_scaled'], name='states_species_8fcff4_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('species', 'energy_scaled', 'j'), name='unique_state'),
        ),
        migrations.AddIndex(
            model_name='transition',
            index=models.Index(fields=['species', 'wave'], name='speciesid_wave'),
        ),
    ]
