# Generated by Django 4.2.25 on 2025-10-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_atom', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transition',
            index=models.Index(fields=['species', 'wave'], name='speciesid_wave'),
        ),
    ]
