# Generated by Django 5.2.7 on 2025-10-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_atom', '0002_transition_speciesid_wave'),
        ('node_common', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['species', 'energy'], name='states_species_c257a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('species', 'energy', 'j', 'term_desc'), name='unique_state'),
        ),
    ]
