# Generated by Django 5.2.7 on 2025-10-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_atom', '0003_state_states_species_c257a2_idx_state_unique_state'),
        ('node_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='species',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='node_common.species'),
        ),
    ]
