# Generated by Django 5.2.7 on 2025-10-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node_atom', '0004_alter_state_species'),
        ('node_common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='wave_linelist',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='iswavelinelist_trans', to='node_common.linelist'),
        ),
    ]
